version: 2
updates:
  - package-ecosystem: composer
    directory: /html
    schedule:
      interval: daily
    groups:
      drupal-core:
        patterns:
          - "drupal/core*"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /html/web/themes/custom/base
    schedule:
      interval: daily
    groups:
      storybook:
        patterns:
          - "*storybook*"
    open-pull-requests-limit: 10
