version: 2
updates:
  - package-ecosystem: composer
    directory: /html
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /html/web/themes/custom/base
    schedule:
      interval: daily
