version: 2
updates:
  - package-ecosystem: composer
    versioning-strategy: increase
    directory: /html
    schedule:
      interval: daily
    groups:
      drupal-core:
        patterns:
          - "drupal/core*"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: /html/web/themes/custom/base_starterkit
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: eslint
        versions:
          - "9.x"
  - package-ecosystem: "docker"
    directory: /docker
    schedule:
      interval: daily
    ignore:
      - dependency-name: "php"
        versions:
          - ">= 8.4"
      - dependency-name: "node"
        versions:
          - ">= 23"
