services:
  traefik:
    profiles:
      - dontstart

  php:
    environment:
      ENVIRONMENT: local
      DRUSH_OPTIONS_URI: "https://${PROJECT_BASE_URL}"

  apache:
    ports:
      - 80:80

  storybook:
    ports:
      - 6006:6006

  mailpit:
    ports:
      - 8025:8025

  pma:
    ports:
      - 3306:80

  supervisor:
    restart: always

  storybook_drupal:
    environment:
      DRUSH_OPTIONS_URI: "https://${PROJECT_BASE_URL}"
