services:
  php:
    image: ${REGISTRY}/${PROJECT_PATH}/php:${IMAGE_TAG}

  apache:
    image: ${REGISTRY}/${PROJECT_PATH}/apache:${IMAGE_TAG}

# Enable for environment with Traefik
#    ports: !override []
#
#networks:
#  traefik_default:
#    external: true
