services:
  php:
    image: ${REGISTRY}/${PROJECT_PATH}/php:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./html/web/sites/default/files:/srv/app/web/sites/default/files

  apache:
    image: ${REGISTRY}/${PROJECT_PATH}/apache:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./html/web/sites/default/files:/srv/app/web/sites/default/files
    ports: !override []
    networks:
      - default
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.apache.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.apache.entrypoints=web"
      - "traefik.http.services.apache.loadbalancer.server.port=80"

networks:
  traefik_default:
    external: true
