services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: app_php
      args: []
    restart: unless-stopped
    environment:
      # Empty value, so it is just taken from environment if exists and ignored otherwise.
      # This is so you can disable whole application using e.g. ".common.env", but enable specific task in console.
      APP_DISABLE:
    env_file:
      - ./env/.common.env
      - ./env/.php.env

  apache:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: apache
    ports:
      - ${HTTP_PORT:-80}:80
    depends_on:
      - php
    env_file:
      - ./env/.common.env
      - ./env/.apache.env
