services:
  php:
    image: ${CI_REGISTRY}/${CI_REPOSITORY_PHP}:${CI_COMMIT_SHA}
    restart: unless-stopped
    volumes:
      - ./html/web/sites/default/files:/srv/app/web/sites/default/files

  cron:
    image: ${CI_REGISTRY}/${CI_REPOSITORY_PHP}:${CI_COMMIT_SHA}
    restart: unless-stopped
    user: 'root'
    entrypoint: ["cron-entrypoint"]
    volumes:
      - ./html/web/sites/default/files:/srv/app/web/sites/default/files
      - ./html/logs:/srv/app/logs
    env_file:
      - ./env/.common.env
      - ./env/.php.env

  apache:
    image: ${CI_REGISTRY}/${CI_REPOSITORY_APACHE}:${CI_COMMIT_SHA}
    restart: unless-stopped
    volumes:
      - ./html/web/sites/default/files:/srv/app/web/sites/default/files
    ports: !override []
    networks:
      - default
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.apache.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.apache.entrypoints=websecure"
      - "traefik.http.routers.apache.tls.certresolver=le"
      - "traefik.http.services.apache.loadbalancer.server.port=80"

networks:
  traefik_default:
    external: true
