name: GrumPHP

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  grumphp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update permissions
        run: sudo chmod -R 777 .

      - name: Spin up environment
        run: make

      - name: Run GrumPHP
        run: |
          docker compose run --rm --no-deps grumphp sh -c 'cd html && composer install'
          docker compose run --rm --no-deps grumphp html/vendor/bin/grumphp run --testsuite coding_standards

      - name: Cleanup
        if: always()
        run: |
          docker compose down
