name: GrumPHP

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  grumphp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Update permissions
        run: sudo chmod -R 777 .

      - name: Spin up environment
        run: task init:local

      - name: Run GrumPHP
        run: |
          docker compose --env-file ./env/.common.env run --rm --no-deps grumphp grumphp run --testsuite coding_standards

      - name: Cleanup
        if: always()
        run: |
          docker compose --env-file ./env/.common.env down
