name: PHPUnit

on: [ pull_request, workflow_dispatch ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Update permissions'
        run: 'sudo chown 1000:1000 -R .'

      - name: 'Spin up environment'
        run: 'docker compose up -d'

      - name: 'Install dependencies'
        run: 'docker compose exec php composer install'

      - name: 'Run PHPUnit'
        run: 'docker compose exec php phpunit -c web/core --group base_test'

      - name: 'Cleanup'
        if: always()
        run: | 
          docker compose down
          sudo chmod 777 -R .
