name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update permissions
        run: sudo chmod -R 777 .

      - name: Spin up environment
        run: make

      - name: Run PHPUnit
        run: docker compose exec php phpunit -c web/core --group web/modules/custom/base_test

      - name: Cleanup
        if: always()
        run: | 
          docker compose down
