name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update permissions
        run: sudo chmod -R 777 .

      - name: Copy PHPUnit docker compose override
        run: cp phpunit.compose.override.yml compose.override.yml

      - name: Spin up environment
        run: make

      - name: Run PHPUnit
        if: github.event_name == 'pull_request'
        run: docker compose exec php phpunit --coverage-clover clover.xml

      - name: Code Coverage Summary Report
        uses: saschanowak/CloverCodeCoverageSummary@1.0.1
        with:
          filename: html/clover.xml

      - name: 'Add Code Coverage to Job Summary'
        run: |
          cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
          cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY

      - name: 'Add Code Coverage Summary as PR Comment'
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-summary.md

      - name: Make code coverage badge
        if: github.ref == 'refs/heads/master'
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: html/clover.xml
          coverage_badge_path: output/coverage.svg
          push_badge: false

      - name: Push badge to image-data branch
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./output
          publish_branch: badges
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Cleanup
        if: always()
        run: | 
          docker compose down
