name: Test build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set production ENV
        run:  ./scripts/prod-env.bash

      - name: Build images
        run: make build
