name: Test build

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Create empty .env files
        run: |
          touch ./env/.common.env
          touch ./env/.php.env
          touch ./env/.apache.env
          cp compose.override.test_build.yml compose.override.yml

      - name: Build PHP and Apache image
        run: task build
